// Code generated by gozz:doc github.com/go-zing/gozz. DO NOT EDIT.

package ztest

var (
	_types_doc = map[interface{}]map[string]string{
		(*Api)(nil):      _doc_Api,
		(*Payload)(nil):  _doc_Payload,
		(*Embedded)(nil): _doc_Embedded,
	}

	_doc_Api = map[string]string{
		"":     "api interface",
		"Get":  "get method",
		"Post": "post method",
	}

	_doc_Payload = map[string]string{
		"":              "query payload",
		"String":        "string field",
		"Int":           "int field",
		"Uint":          "uint field",
		"Map":           "map field",
		"MapPointer":    "map field with pointer element",
		"Slice":         "slice field",
		"SlicePointer":  "slice field with pointer element",
		"Struct":        "anonymous struct field",
		"StructPointer": "anonymous struct field with pointer element",
		"Bytes":         "bytes field",
		"Refer":         "refer struct",
		"Exported":      "exported recursive",
		"unexported":    "unexported recursive",
	}

	_doc_Embedded = map[string]string{
		"Struct2": "struct field with pointer element",
		"Payload": "anonymous field with pointer element",
	}
)

func (Payload) FieldDoc(f string) string { return _doc_Payload[f] }

func (Embedded) FieldDoc(f string) string { return _doc_Embedded[f] }
