// Code generated by gozz:option github.com/go-zing/gozz. DO NOT EDIT.

package zsql

import (
	"database/sql"
)

// apply functional options for txOption
func (o *txOption) applyOptions(opts ...func(*txOption)) {
	for _, opt := range opts {
		opt(o)
	}
}

func WithSqlTxOptions(v *sql.TxOptions) func(*txOption) {
	return func(o *txOption) { o.SqlTxOptions = v }
}

func WithRollback(v func(rollback func() error, cause error) error) func(*txOption) {
	return func(o *txOption) { o.Rollback = v }
}

func WithRecovery(v func(exception interface{}) error) func(*txOption) {
	return func(o *txOption) { o.Recovery = v }
}
