// Code generated by gozz:doc github.com/go-zing/gozz. DO NOT EDIT.

package ztree

var (
	_types_doc = map[interface{}]map[string]string{
		(*_T0)(nil):    _doc__T0,
		(*_field)(nil): _doc__field,
	}

	_doc__T0 = map[string]string{
		"":       "type for testing",
		"Field":  "export field with pointer struct type",
		"Buff":   "export field with interface reader type",
		"_field": "unexported field interface",
	}

	_doc__field = map[string]string{
		"":     "field interface",
		"Read": "read function",
	}
)

func (_T0) FieldDoc(f string) string { return _doc__T0[f] }
