// Code generated by gozz:option github.com/go-zing/gozz. DO NOT EDIT.

package ztree

import ()

// apply functional options for Option
func (o *Option) applyOptions(opts ...func(*Option)) {
	for _, opt := range opts {
		opt(o)
	}
}

func WithUnexported(v bool) func(*Option) { return func(o *Option) { o.Unexported = v } }
