// Code generated by gozz:option github.com/go-zing/gozz. DO NOT EDIT.

package zapi

import (
	"reflect"
)

// apply functional options for Parser
func (o *Parser) applyOptions(opts ...func(*Parser)) {
	for _, opt := range opts {
		opt(o)
	}
}

func WithDocFunc(v func(p reflect.Type, field string) string) func(*Parser) {
	return func(o *Parser) { o.docFunc = v }
}

func WithTypes(v map[reflect.Type]*PayloadType) func(*Parser) { return func(o *Parser) { o.types = v } }
